#=====================================================================================
name: enclave
description: Enclave Project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#=====================================================================================
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#=====================================================================================
version: 1.2.7+30 # 2022.04.30 - not submitted

#=====================================================================================
environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
#=====================================================================================
dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^1.13.1
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: ^3.3.9
  firebase_crashlytics: ^2.5.3
  cloud_firestore: ^3.1.10
  cloud_functions: ^3.2.9
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  firebase_remote_config: ^2.0.2

  # Updated to work with new core only plugins (no new changes):
  # firebase_admob: ^0.11.2
  firebase_analytics: ^9.1.2
  firebase_database: ^9.0.8
  firebase_dynamic_links: ^4.0.8
  firebase_in_app_messaging: ^0.6.0+9
  firebase_performance: ^0.8.0+7

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core_platform_interface: ^4.2.5
  firebase_storage_platform_interface: ^4.1.1

  # Add the dependency for the FlutterFire plugin for Google Analytics
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  # google sign-in
  google_sign_in: ^5.2.4
  firebase_phone_auth_handler: ^1.0.1


  # allows you to add hex color codes to your flutter projects
  hexcolor: ^2.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  flutter_launcher_icons: ^0.9.2

  # generate UUID
  uuid: ^3.0.6

  # GetX packages
  get: ^4.6.1
  get_storage: ^2.0.3

  # form builder
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.6.1

  # material icon
  material_design_icons_flutter: ^5.0.6595

  # path tools
  path_provider: ^2.0.9
  path: ^1.8.0 # do not upgrade

  # http
  http: ^0.13.4

  # zip archive
  archive: ^3.2.1

  # syncFusion pdf viewer, DataGrid
  syncfusion_flutter_pdfviewer: ^19.4.54-beta
  syncfusion_flutter_datagrid: ^19.4.54

  # photo view
  photo_view: ^0.13.0

  # direct caller
  flutter_phone_direct_caller: ^2.1.0

  # flutter sound
  audioplayers: ^0.20.1
  # flutter_sound: ^9.1.3

  # send sms
  flutter_sms: ^2.3.2 # import 'package:flutter_sms/flutter_sms.dart';

  # auto size text
  auto_size_text: ^3.0.0 # import 'package:auto_size_text/auto_size_text.dart';

  # image picker
  image_picker: ^0.8.4+10
  # image cropper
  image_cropper: ^1.5.0
  # cached network image
  # cached_network_image: ^3.2.0
  # firebase image
  firebase_image: ^1.1.1

  # device info plus
  device_info_plus: ^3.2.2

  # package info plus
  package_info_plus: ^1.4.0

  # url launch, email sending
  url_launcher: ^6.0.20
  # url launch, email sending
  # flutter_email_sender: ^5.0.2 # import 'package:flutter_email_sender/flutter_email_sender.dart';

  # excel
  spreadsheet_decoder: ^2.0.1

  # rich text editor
  # zefyr: ^1.0.0-rc.5

  # Build the beautiful settings screen UI in one moment with Settings UI for Flutter
  flutter_settings_screens: ^0.3.2-null-safety

  # ObjectBox
  objectbox: ^1.4.0
  objectbox_flutter_libs: any
  # excel: 2.0.0-null-safety-3 # import 'package:excel/excel.dart';

  # master_detail_scaffold: contains widgets that help implement a responsive master-detail layout
  master_detail_scaffold: ^2.0.0

  # flutter_advanced_avatar
  # flutter_advanced_avatar: ^1.0.0+1

  # scrollable_positioned_list: allows scrolling to a specific item in the list. Also allows determining what items are currently visible
  scrollable_positioned_list: ^0.2.3

  # A plugin for handling Vibration API on iOS, Android, and web
  flutter_vibrate: ^1.3.0

  # Adaptive Scrollbar is a library that allows you to create one or more desktop-style scrollbars on a single screen,
  # each of which is bound only to its own object and placed in its own place on the screen.
  adaptive_scrollbar: ^2.1.2

  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text
  intl: ^0.17.0

  # This is a flutter plugin that makes it easy to enable fullscreen in flutter application
  # fullscreen: ^1.0.3

  # A Flutter plugin that makes it possible to:
  #Check if a user has the most recent version of your app installed.
  #Show the user an alert with a link to the appropriate app store page
  # new_version: ^0.3.0

  # advance image picker
  # advance_image_picker: ^0.1.5+6 # import 'package:advance_image_picker/advance_image_picker.dart';

  # native splash
  # to create: 'flutter pub run flutter_native_splash:create'
  # to remove: 'flutter pub run flutter_native_splash:remove'
  #flutter_native_splash: ^1.3.2

  # international phone number
  # intl_phone_field: ^2.1.0 # import 'package:intl_phone_field/intl_phone_field.dart';

  # search bar
  # search_app_bar: ^1.0.2+2 # import 'package:search_app_bar/search_app_bar.dart';

#=====================================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

  # build_runner for ObjectBox
  build_runner: ^2.1.7
  objectbox_generator: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#=====================================================================================
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/icon/
    - assets/image/
    - assets/pdf/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages