/// Generated by Flutter GetX Starter on 2022-01-01 00:44
import 'package:get/get_state_manager/src/simple/get_controllers.dart';

import '../../pages/splash/splash_state.dart';

class SplashLogic extends GetxController {
  final state = SplashState();

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}
