/// Generated by Flutter GetX Starter on 2022-01-01 00:44
import 'package:get/get_state_manager/src/simple/get_controllers.dart';

import 'url_state.dart';

class UrlLogic extends GetxController {
  final state = UrlState();

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }

  Future<bool> initUrlPageAsync() async {
    return true;
  }
}
