// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_sAAyGNQeycL6mQO4uOPjAODu-fpr5A',
    appId: '1:66429003884:web:05ec150460b37b88b41049',
    messagingSenderId: '66429003884',
    projectId: 'enclave-development-8381f',
    authDomain: 'enclave-development-8381f.firebaseapp.com',
    databaseURL: 'https://enclave-development-8381f-default-rtdb.firebaseio.com',
    storageBucket: 'enclave-development-8381f.appspot.com',
    measurementId: 'G-MTQFZ115TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIs6ZZbTRKZep955gYn4k-26hzkosXT0M',
    appId: '1:66429003884:android:77703b55af55a11fb41049',
    messagingSenderId: '66429003884',
    projectId: 'enclave-development-8381f',
    databaseURL: 'https://enclave-development-8381f-default-rtdb.firebaseio.com',
    storageBucket: 'enclave-development-8381f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhjzPX8vdkPU8JQabADHHiO1bzYXoqZHo',
    appId: '1:66429003884:ios:01c78247fb684175b41049',
    messagingSenderId: '66429003884',
    projectId: 'enclave-development-8381f',
    databaseURL: 'https://enclave-development-8381f-default-rtdb.firebaseio.com',
    storageBucket: 'enclave-development-8381f.appspot.com',
    androidClientId: '66429003884-ia66108ii0du1c9gf8c054c7id1djptj.apps.googleusercontent.com',
    iosClientId: '66429003884-dl16s3mpatnkaeh1sr8honanffeii7re.apps.googleusercontent.com',
    iosBundleId: 'com.lgsdiamant.enclave',
  );
}
